### ISSUE TITLE
Some Questions, log capabilities, hanging processes

### ISSUE THREAD

**Issue by klodoma** [mmucklo/DtcQueueBundle#119]
I am evaluating this bundle, I have several questions

1. Are there any log capabilities for a job? I see there is a message, but I couldn't find an example of using it. 
2. If the "daemon" dies with error, and the job was "running" it just stays running 4ever. Should we periodically check for errors or what is the idea?
3. Can we kill jobs?

**Comment by mmucklo** [comment]
@klodoma Let me try to answer your questions:

   1. You can use setMessage() to set a message on the currently running job that should get persisted when the job is finished / archived, otherwise if there's an exception during the running of the job, the job's message should have the details of the exception recorded. However other than that you'll just need to log to stdout  / stderr and pick it up by redirecting the output of each run to a file (or using the tee command if you want both), or inject a logger service such as monolog into your worker and have messages sent to it spool off somewhere.

In the [CHANGELOG](//github.com/mmucklo/DtcQueueBundle/master/CHANGELOG.md) it says the following:

```
      * Access to Current Job (inspired by the fork of @wzele)
         * $this->getCurrentJob() will return the current Job object during a worker's method invocation.
            * This may be useful if you want to record some message by calling $this->getCurrentJob()->setMessage('some message');
            * However only Doctrine Jobs are persisted on SUCCESS
```

It's probably not a bad idea for me to document that somewhere else.

   2. These are known as "STALLED" jobs. There's a prune command that can be run manually or periodically to remove them.

```
# prune stalled jobs
bin/console dtc:queue:prune stalled

# prune stalled jobs older than one day
bin/console dtc:queue:prune stalled --older 1d
```

   If they stalled because a machine crashed, you may just want to "reset" them if they are important.

There's a reset command which will restart them:

```
bin/console dtc:queue:reset
```

   3. What do you mean by kill? Stop jobs that are in progress? Presently no, not unless you kill the PHP process that's running them. You can set a timeout on the dtc:queue:run command though that should cause the PHP process to hard exit if it runs for longer than the timeout value.

Hope this helps, and sorry for the delay in response.

**Comment by klodoma** [comment]
@mmucklo great!

Thanks a lot for the comprehensive answers. 

I like this bundle, I think it has a lot of potential and it achieves already a lot of stuff. I also have several use-cases where I can use it, I'll try to provide some feedback withing the next months. 

Thanks again.

**Comment by mmucklo** [comment]
@klodoma 

Thanks for the feedback, hope it works out for you.
